Homework 6 Introduction to Data Science Macy Balabon

Part 1: Data Loading and Exploration

In [1]:
from sklearn.datasets import fetch_california_housing

# Load the housing dataset
housing = fetch_california_housing()

In [2]:
# Import neccesary libraries
import pandas as pd
import numpy as np

In [3]:
X = pd.DataFrame(housing.data, columns = housing.feature_names) 
y = pd.Series(housing.target, name='med_house_value')

In [5]:
# Display the first five rows of the dataset
print("Dataset preview:")
print(X.head())
print("\nTarget variable preview:")
print(y.head())

Dataset preview:
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25  

Target variable preview:
0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: med_house_value, dtype: float64


In [6]:
#Print the feature names and check for missing values

print("\nFeature Names:")
print(X.columns)

print("\nMissing Values in Each Column:")
print(X.isnull().sum())


Feature Names:
Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='object')

Missing Values in Each Column:
MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64


In [7]:
#Generate summary statistics (mean, min, max, etc.)
print("\nSummary Statistics for Feature Variables:")
print(X.describe())

print("\nSummary Statistics for Target Variable:")
print(y.describe())


Summary Statistics for Feature Variables:
             MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.3500

Part 2: Linear Regression on Unscaled Data

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score

In [9]:
#Split the dataset into training and test sets
X_train_raw, X_test_raw, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
#Train a linear regression model on the unscaled data using sklearn.linear_model.LinearRegression
lin_reg_raw = LinearRegression()
lin_reg_raw.fit(X_train_raw, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [11]:
#Make predictions on the test set
y_pred_raw = lin_reg_raw.predict(X_test_raw)

In [12]:
#Evaluate model performance using the following metrics

#Mean Squared Error (MSE)
mse_raw = mean_squared_error(y_test, y_pred_raw)

#Root Mean Squared Error (RMSE)

rmse_raw = root_mean_squared_error(y_test, y_pred_raw)

#R² Score

r2_raw = r2_score(y_test, y_pred_raw)

print("Unscaled Data Model:")
print(f"Mean Squared Error: {mse_raw:.2f}")
print(f"Root Squared Error: {rmse_raw:.2f}")
print(f"R² Score: {r2_raw:.2f}")

Unscaled Data Model:
Mean Squared Error: 0.56
Root Squared Error: 0.75
R² Score: 0.58


Interpretation Questions (Answer in Markdown cells):

What does the R² score tell us about model performance?

Which features seem to have the strongest impact on predictions based on the model’s coefficients?

How well do the predicted values match the actual values?


Part 3: Feature Selection and Simplified Model

In [ ]:
# View the model's coefficients
print("Model Coefficients (Unscaled):")
print(pd.Series(lin_reg_raw.coef_,
                index=X.columns))
print("\nModel Intercept (Unscaled):")
print(pd.Series(lin_reg_raw.intercept_))

Model Coefficients (Unscaled):
MedInc        0.448675
HouseAge      0.009724
AveRooms     -0.123323
AveBedrms     0.783145
Population   -0.000002
AveOccup     -0.003526
Latitude     -0.419792
Longitude    -0.433708
dtype: float64

Model Intercept (Unscaled):
0   -37.023278
dtype: float64


The features i'm selecting for the dataset to build a simplified model are AveBedrms, MedInc, and Longitude because they have the largest coefficients in the full linear regression model.AveBedrms is 0.783145, MedInc is 0.448675, and Longitude is -0.433708. So, the variables have the biggest impact on the median house value.

In [14]:
#Select three features
feature_vars_selected = ["AveBedrms", "MedInc", "Longitude"]

In [ ]:
#selected variables dataframe

X_selected = pd.DataFrame(X[feature_vars_selected])

#Split the dataset into training and test sets
X_train_selected, X_test_selected, y_train_selected, y_test_selected = train_test_split(X_selected, y, test_size=0.2, random_state=42)

#Train a new linear regression model using only these three features

lin_reg_selected = LinearRegression()
lin_reg_selected.fit(X_train_selected, y_train_selected)



,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [18]:
#Make predictions on the test set
y_pred_selected = lin_reg_selected.predict(X_test_selected)

In [21]:
#Evaluate model performance

#Mean Squared Error (MSE)
mse_selected = mean_squared_error(y_test, y_pred_selected)

#Root Mean Squared Error (RMSE)

rmse_selected = root_mean_squared_error(y_test, y_pred_selected)

#R² Score

r2_selected = r2_score(y_test, y_pred_selected)

print("Selected Data Model:")
print(f"Mean Squared Error: {mse_selected:.2f}")
print(f"Root Squared Error: {rmse_selected:.2f}")
print(f"R² Score: {r2_selected:.2f}")


Selected Data Model:
Mean Squared Error: 0.71
Root Squared Error: 0.84
R² Score: 0.46


The Unscaled Data Model:
Mean Squared Error: 0.56
Root Squared Error: 0.75
R² Score: 0.58

Evaluate the performance of this simplified model and compare it to the full model



Interpretation Questions: (5 pts)
How does the simplified model compare to the full model?


Would you use this simplified model in practice? Why or why not?

